export const ROUTER_PAGES_PARTS = {
  INITIAL: '',
  HOME_USER: 'my',
  CHECK: 'check',
  ADMIN: 'admin',
  HOME_ADMIN: 'my',
  NEW_COMPANY_ORDER: 'order',
  NEW_COMPANY_ORDER_CODE_ID: 'code'
};

export const ROUTER_PAGES = {
  admin: {
    ADMIN: `/${ROUTER_PAGES_PARTS.ADMIN}`,
    ADMIN_ORDERS: `/${ROUTER_PAGES_PARTS.ADMIN}/${ROUTER_PAGES_PARTS.HOME_ADMIN}`,
    NEW_ORDER: `/${ROUTER_PAGES_PARTS.ADMIN}/${ROUTER_PAGES_PARTS.HOME_ADMIN}/${ROUTER_PAGES_PARTS.NEW_COMPANY_ORDER}`,
    NEW_ORDER2: `/${ROUTER_PAGES_PARTS.HOME_ADMIN}/${ROUTER_PAGES_PARTS.NEW_COMPANY_ORDER}`
  },
  user: {
    HOME: `/${ROUTER_PAGES_PARTS.HOME_USER}`,
    HOME_CHECk: `/${ROUTER_PAGES_PARTS.HOME_USER}/${ROUTER_PAGES_PARTS.CHECK}`
  },
  INITIAL: `/${ROUTER_PAGES_PARTS.INITIAL}`
};
